# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tokensmith < Formula
  desc "Terminal management game where your real AI-coding tokens fuel an AI company"
  homepage "https://github.com/curtis1215/tokensmith"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/curtis1215/tokensmith/releases/download/v0.4.0/tokensmith_darwin_amd64.tar.gz"
      sha256 "e150b971b026a3bda5830ca316f011409ee9217d5051a440b3b5acb998521870"

      define_method(:install) do
        bin.install "tokensmith"
        bin.install "tokensmithd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/curtis1215/tokensmith/releases/download/v0.4.0/tokensmith_darwin_arm64.tar.gz"
      sha256 "466de849d8d4e38c9b613ecbe1923b53c55f15b60cdb467e18c843b0f78d1b4b"

      define_method(:install) do
        bin.install "tokensmith"
        bin.install "tokensmithd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/curtis1215/tokensmith/releases/download/v0.4.0/tokensmith_linux_amd64.tar.gz"
      sha256 "93dacda27012961c257501997c23a1cc5eb2bf5affbd807725bf272397eecc58"
      define_method(:install) do
        bin.install "tokensmith"
        bin.install "tokensmithd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/curtis1215/tokensmith/releases/download/v0.4.0/tokensmith_linux_arm64.tar.gz"
      sha256 "27aea8d52a2b14aef2b1428791e862eac3ada9b2f6f37e870a8e84cd389e1edd"
      define_method(:install) do
        bin.install "tokensmith"
        bin.install "tokensmithd"
      end
    end
  end

  def caveats
    <<~EOS
      Start the background token-harvest daemon with:
        brew services start tokensmith
      Then play the game with:
        tokensmith
    EOS
  end

  service do
    run [opt_bin/"tokensmithd"]
    keep_alive true
    log_path var/"log/tokensmithd.log"
    error_log_path var/"log/tokensmithd.log"
  end

  test do
    assert_match "tokensmith", shell_output("#{bin}/tokensmith --version")
  end
end
