# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tokensmith < Formula
  desc "Terminal management game where your real AI-coding tokens fuel an AI company"
  homepage "https://github.com/curtis1215/tokensmith"
  version "0.5.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/curtis1215/tokensmith/releases/download/v0.5.3/tokensmith_darwin_amd64.tar.gz"
      sha256 "ce039f11820efecd6fa9a465a678218eb56944c5f4b652c232e254d526535a9a"

      define_method(:install) do
        bin.install "tokensmith"
        bin.install "tokensmithd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/curtis1215/tokensmith/releases/download/v0.5.3/tokensmith_darwin_arm64.tar.gz"
      sha256 "f32e9b56ded0d001ebc34babb5181a10970b85f3d28ff273bfe44f736c32b8f1"

      define_method(:install) do
        bin.install "tokensmith"
        bin.install "tokensmithd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/curtis1215/tokensmith/releases/download/v0.5.3/tokensmith_linux_amd64.tar.gz"
      sha256 "ef0324f2c3c9487cf1be069b9020e5c9e2c1d4ea04590136123d15d96da9c404"
      define_method(:install) do
        bin.install "tokensmith"
        bin.install "tokensmithd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/curtis1215/tokensmith/releases/download/v0.5.3/tokensmith_linux_arm64.tar.gz"
      sha256 "0bfbcd5a477a9ab833f1a1b68c2b2bdbbcdf8689dda1d4dd92a14da9cd16cb76"
      define_method(:install) do
        bin.install "tokensmith"
        bin.install "tokensmithd"
      end
    end
  end

  def caveats
    <<~EOS
      Start the background token-harvest daemon with:
        brew services start tokensmith
      Then play the game with:
        tokensmith
    EOS
  end

  service do
    run [opt_bin/"tokensmithd"]
    keep_alive true
    log_path var/"log/tokensmithd.log"
    error_log_path var/"log/tokensmithd.log"
  end

  test do
    assert_match "tokensmith", shell_output("#{bin}/tokensmith --version")
  end
end
