# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tokensmith < Formula
  desc "Terminal management game where your real AI-coding tokens fuel an AI company"
  homepage "https://github.com/curtis1215/tokensmith"
  version "0.7.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/curtis1215/tokensmith/releases/download/v0.7.1/tokensmith_darwin_amd64.tar.gz"
      sha256 "b60d2f86604efefa0a3c9f1ac0891d2266c4a67836ff9f28c44c3380dad0d43b"

      define_method(:install) do
        bin.install "tokensmith"
        bin.install "tokensmithd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/curtis1215/tokensmith/releases/download/v0.7.1/tokensmith_darwin_arm64.tar.gz"
      sha256 "93c329cd91a5a4a716f98efb41420b9bffe85db60c497eec8a0dda4588002ff3"

      define_method(:install) do
        bin.install "tokensmith"
        bin.install "tokensmithd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/curtis1215/tokensmith/releases/download/v0.7.1/tokensmith_linux_amd64.tar.gz"
      sha256 "1e5076e4ed884f9010df44e9da5205609eb82c9834c1014b060f7cddd4e26cac"
      define_method(:install) do
        bin.install "tokensmith"
        bin.install "tokensmithd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/curtis1215/tokensmith/releases/download/v0.7.1/tokensmith_linux_arm64.tar.gz"
      sha256 "fbbaf01e07b50f7216f87fdeb9d692a9ed19df3d4de106f849acbe3991085268"
      define_method(:install) do
        bin.install "tokensmith"
        bin.install "tokensmithd"
      end
    end
  end

  def caveats
    <<~EOS
      Start the background token-harvest daemon with:
        brew services start tokensmith
      Then play the game with:
        tokensmith
    EOS
  end

  service do
    run [opt_bin/"tokensmithd"]
    keep_alive true
    log_path var/"log/tokensmithd.log"
    error_log_path var/"log/tokensmithd.log"
  end

  test do
    assert_match "tokensmith", shell_output("#{bin}/tokensmith --version")
  end
end
